'use client';
import { useEffect, useRef, useState } from 'react';
const portraits=['makise-kurisu-2.webp','atam-1.webp','kintaro-2.webp','makise-kurisu-1.webp','atam-2.webp','kintaro-1.webp'].map(n=>`https://www.xkintaro.com/hero-slider/${n}`);
const techGroups=[['Frontend Technologies',['React','Next.js','Tailwind CSS','Framer Motion','TypeScript','JavaScript','HTML5','CSS3']],['Backend Technologies',['Node.js','PHP','Laravel','ASP.NET','Rust','C#','Python']],['Databases & ORMs',['PostgreSQL','MySQL','MongoDB','Prisma','Neon']],['Tools & Infrastructure',['Git','Vercel','Tauri']]];
const techSlugs:Record<string,string>={'Next.js':'nextjs','Tailwind CSS':'tailwindcss','Framer Motion':'framermotion','Node.js':'nodejs','ASP.NET':'aspnet','C#':'csharp'};
const techIcon=(name:string)=>name==='Neon'?'https://www.xkintaro.com/stack/neon.png':`https://www.xkintaro.com/stack/${techSlugs[name]||name.toLowerCase().replace(/[^a-z0-9]/g,'')}.svg`;
const projects=[['Aether Media','Media Tool','2026','20260427093247885.jpg'],['Aether JS','Library','2026','20260427093247620.jpg'],['File Manager','Web Application','2025','20260305210513749.jpg']];
const years=[['2022','I first got introduced to software development in high school. I learned programming fundamentals with C#.','C#'],['2023','I started developing static and dynamic websites and exploring databases.','HTML · CSS · ASP.NET · MySQL'],['2024','I refined my interface development skills and continued building practical systems.','HTML · CSS · ASP.NET'],['2025','I moved into modern tools and created websites and desktop applications.','React · Node.js · MongoDB'],['2026','I now focus on Laravel, Next.js and PostgreSQL while building personal products.','Laravel · Next.js · PostgreSQL']];
function SectionTitle({number,title}:{number:string;title:string}){return <div className="section-title reveal"><span>[{number}]</span><h2>{title}</h2></div>}
function Marquee(){const w='RADICAL TRANSPARENCY · INTENTIONAL MINIMALISM · ARCHITECTURAL INTEGRITY · FIRST PRINCIPLES THINKING · PERFORMANCE WITHOUT COMPROMISE · SCALABLE VISION · ';return <div className="marquee" aria-hidden="true"><div>{w.repeat(3)}</div></div>}
export default function Home(){const[light,setLight]=useState(false);const[menu,setMenu]=useState(false);const projectTrack=useRef<HTMLDivElement>(null);useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));return()=>io.disconnect()},[]);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const targets=Array.from(document.querySelectorAll<HTMLElement>('.hero-copy,.portrait-wall,.content-section>*,.marquee>div,.projects-intro,.project-card'));let raf=0;const update=()=>{raf=0;const vh=innerHeight;targets.forEach(el=>{let blur=0;let opacity=1;if(el.closest('.hero')){const progress=Math.min(1,scrollY/(vh*.72));blur=progress*10;opacity=1-progress*.42}else{const effectArea=el.closest<HTMLElement>('section')??el;const rect=effectArea.getBoundingClientRect();const viewportCenter=vh/2;const distance=rect.top>viewportCenter?rect.top-viewportCenter:rect.bottom<viewportCenter?viewportCenter-rect.bottom:0;const progress=Math.min(1,distance/(vh*.88));blur=Math.max(0,(progress-.18)*11);opacity=1-Math.max(0,progress-.48)*.5}el.style.setProperty('--scroll-blur',`${blur.toFixed(2)}px`);el.style.setProperty('--scroll-opacity',opacity.toFixed(3))})};const onMove=()=>{if(!raf)raf=requestAnimationFrame(update)};addEventListener('scroll',onMove,{passive:true});addEventListener('resize',onMove);update();return()=>{removeEventListener('scroll',onMove);removeEventListener('resize',onMove);if(raf)cancelAnimationFrame(raf)}},[]);useEffect(()=>{let raf=0;const update=()=>{raf=0;const section=document.getElementById('projects');const track=projectTrack.current;if(!section||!track)return;if(innerWidth<901){track.style.transform='none';return}const range=Math.max(1,section.offsetHeight-innerHeight);const progress=Math.max(0,Math.min(1,(scrollY-section.offsetTop)/range));const distance=Math.max(0,track.scrollWidth-innerWidth+innerWidth*.05);track.style.transform=`translate3d(${-progress*distance}px,0,0)`};const onMove=()=>{if(!raf)raf=requestAnimationFrame(update)};addEventListener('scroll',onMove,{passive:true});addEventListener('resize',onMove);update();return()=>{removeEventListener('scroll',onMove);removeEventListener('resize',onMove);if(raf)cancelAnimationFrame(raf)}},[]);useEffect(()=>{document.documentElement.dataset.theme=light?'light':'dark'},[light]);const jump=(id:string)=>{document.querySelector(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};return <main>
<header><button className="brand" onClick={()=>jump('#home')}>MOGHRABY</button><nav className={menu?'open':''}>{['Home','About','Stack','Projects','Roadmap','Contact'].map(x=><button key={x} onClick={()=>jump(`#${x.toLowerCase()}`)}>{x}</button>)}</nav><div className="controls"><button aria-label="Toggle theme" onClick={()=>setLight(!light)}>{light?'●':'☾'}</button><button className="menu" aria-label="Menu" onClick={()=>setMenu(!menu)}>☰</button></div></header>
<section id="home" className="hero"><div className="noise"/><div className="stars"/><div className="hero-copy reveal visible"><p className="eyebrow">WEB DEVELOPER · 2026</p><h1>MOHAMMAD<br/><span>MOGHRABY</span></h1><p className="intro">I&apos;m someone who loves <b>learning new things</b> and constantly tries to put what I learn into practice. I develop <i>web</i> and <i>desktop</i> applications. I enjoy working with simple, <b>practical</b>, and <b>sustainable</b> tools.</p><div className="hero-actions"><button className="primary" onClick={()=>jump('#contact')}>CONTACT ME <span>→</span></button><button className="text-btn" onClick={()=>jump('#projects')}>◉ &nbsp; EXPLORE PROJECTS</button></div></div><div className="portrait-wall" aria-hidden="true">{portraits.map((src,i)=><div className={`portrait p${i+1}`} key={src}><img src={src} alt=""/></div>)}</div></section>
<section id="about" className="content-section about"><div className="about-grid"><aside className="about-side"><SectionTitle number="001" title="About"/><div className="badge-rig reveal" aria-hidden="true"><div className="badge-line"><i/><i/></div><div className="badge-card"><div className="badge-avatar">♙</div><b>MOHAMMAD MOGHRABY</b><span>Web Developer</span></div></div></aside><div className="about-copy"><h3 className="reveal">I&apos;m a <em>Web Developer</em> focused on building <strong>clean and sustainable systems</strong>.</h3><p className="reveal">I&apos;m someone who loves <b>learning new things</b> and constantly tries to put what I learn into practice. I develop <i>web</i> and <i>desktop</i> applications. I enjoy working with simple, <b>practical</b>, and <b>sustainable</b> tools.</p><button className="about-link reveal">READ FULL VERSION <span>→</span></button></div></div></section><Marquee/>
<section id="stack" className="content-section"><SectionTitle number="002" title="Stack"/><div className="stack-list">{techGroups.map(([title,items],i)=><article className="tech-row reveal" key={title as string}><div className="tech-heading"><span>0{i+1}</span><h3>{title}</h3></div><div className="tech-items">{(items as string[]).map(item=><div className="tech-item" key={item}><img src={techIcon(item)} alt=""/><b>{item}</b></div>)}</div></article>)}</div></section><Marquee/>
<section id="projects" className="projects"><div className="projects-sticky"><div className="project-track" ref={projectTrack}><div className="projects-intro"><SectionTitle number="003" title="Projects"/><p className="reveal">A collection of <em>experiments</em>, <em>products</em>, and <em>digital artifacts</em> forged in the <strong>void</strong>.</p><div className="explore-line"><i/>SCROLL TO EXPLORE</div></div>{projects.map(([name,type,year,img])=><article className="project-card reveal" key={name}><div className="project-image"><img src={`https://www.xkintaro.com/projects/${img}`} alt={name}/><div className="project-meta"><span>{type}</span><b>{year}</b></div><h3>{name}</h3></div></article>)}</div></div></section><Marquee/>
<section id="roadmap" className="content-section roadmap"><SectionTitle number="004" title="Roadmap"/><p className="section-lead reveal">A timeline of the experiences and technologies that shaped my software journey.</p><div className="timeline reveal"><div className="timeline-base"/><div className="timeline-fill"/>{years.map(([year,desc,tags],i)=><article className={`year reveal ${i%2?'year-right':'year-left'}`} style={{transitionDelay:`${i*110}ms`}} key={year}><div className="year-dot"><i/></div><div className="year-card"><span className="year-index">0{i+1}</span><h3>{year}</h3><p>{desc}</p><div className="year-tags">{tags.split(' · ').map(tag=><b key={tag}>{tag}</b>)}</div><em>{year.slice(2)}</em></div></article>)}</div></section><Marquee/>
<section id="contact" className="content-section contact"><SectionTitle number="005" title="Contact"/><h3 className="reveal">Whether we start fresh to bring a project to life or take an existing system further.</h3><div className="contact-details reveal"><a className="contact-row" href="mailto:mhmdmghrby516@gmail.com"><span>Send an Email</span><div><b>mhmdmghrby516@gmail.com</b><i>↗</i></div></a><a className="contact-row" href="tel:+963938974788"><span>Direct Line</span><div><b>0938974788</b><i>↗</i></div></a></div><footer><div className="copyright">© 2026 <b>MOHAMMAD MOGHRABY.</b> All rights reserved.</div><div className="social-pills"/></footer></section>
</main>}
